// riddleDefaults.js
export const RIDDLE_DEFAULTS = {
    "Location Based Riddle": {
        Standard: { radius: 60, allowedTime: 320, deductionPercent: 12 },
        Indoor: { radius: 25, allowedTime: 180, deductionPercent: 7 },
        "Bachelor Game": { radius: 22, allowedTime: 210, deductionPercent: 6 },
        "Bachelorette Game": { radius: 18, allowedTime: 190, deductionPercent: 8 },
        "Bachelor Game No Action Pack": { radius: 24, allowedTime: 205, deductionPercent: 6 },
        "Bachelorette Game No Action Pack": { radius: 19, allowedTime: 195, deductionPercent: 7 },
        "Cristmas Adventures": { radius: 23, allowedTime: 215, deductionPercent: 9 },
        "Cristmas Adventures No Action Pack": { radius: 21, allowedTime: 185, deductionPercent: 8 },
    },
    "Augmented Reality": {
        Standard: { radius: 55, allowedTime: 310, deductionPercent: 11 },
        Indoor: { radius: 18, allowedTime: 170, deductionPercent: 6 },
        "Bachelor Game": { radius: 21, allowedTime: 220, deductionPercent: 7 },
        "Bachelorette Game": { radius: 17, allowedTime: 180, deductionPercent: 9 },
        "Bachelor Game No Action Pack": { radius: 20, allowedTime: 200, deductionPercent: 8 },
        "Bachelorette Game No Action Pack": { radius: 16, allowedTime: 175, deductionPercent: 7 },
        "Cristmas Adventures": { radius: 22, allowedTime: 210, deductionPercent: 10 },
        "Cristmas Adventures No Action Pack": { radius: 18, allowedTime: 190, deductionPercent: 9 },
    },
    "Multiple Choice": {
        Standard: { radius: 52, allowedTime: 330, deductionPercent: 13 },
        Indoor: { radius: 23, allowedTime: 160, deductionPercent: 8 },
        "Bachelor Game": { radius: 19, allowedTime: 230, deductionPercent: 5 },
        "Bachelorette Game": { radius: 15, allowedTime: 170, deductionPercent: 10 },
        "Bachelor Game No Action Pack": { radius: 18, allowedTime: 210, deductionPercent: 9 },
        "Bachelorette Game No Action Pack": { radius: 14, allowedTime: 165, deductionPercent: 8 },
        "Cristmas Adventures": { radius: 20, allowedTime: 220, deductionPercent: 11 },
        "Cristmas Adventures No Action Pack": { radius: 17, allowedTime: 180, deductionPercent: 10 },
    },
    "Action Pack": {
        Standard: { radius: 65, allowedTime: 340, deductionPercent: 14 },
        Indoor: { radius: 28, allowedTime: 150, deductionPercent: 9 },
        "Bachelor Game": { radius: 25, allowedTime: 240, deductionPercent: 8 },
        "Bachelorette Game": { radius: 20, allowedTime: 160, deductionPercent: 11 },
        "Bachelor Game No Action Pack": { radius: 26, allowedTime: 215, deductionPercent: 10 },
        "Bachelorette Game No Action Pack": { radius: 22, allowedTime: 155, deductionPercent: 9 },
        "Cristmas Adventures": { radius: 27, allowedTime: 225, deductionPercent: 12 },
        "Cristmas Adventures No Action Pack": { radius: 23, allowedTime: 170, deductionPercent: 11 },
    },
    "Mini Game": {
        Standard: { radius: 48, allowedTime: 350, deductionPercent: 15 },
        Indoor: { radius: 30, allowedTime: 140, deductionPercent: 10 },
        "Bachelor Game": { radius: 28, allowedTime: 250, deductionPercent: 9 },
        "Bachelorette Game": { radius: 24, allowedTime: 150, deductionPercent: 12 },
        "Bachelor Game No Action Pack": { radius: 29, allowedTime: 220, deductionPercent: 11 },
        "Bachelorette Game No Action Pack": { radius: 25, allowedTime: 145, deductionPercent: 10 },
        "Cristmas Adventures": { radius: 31, allowedTime: 230, deductionPercent: 13 },
        "Cristmas Adventures No Action Pack": { radius: 26, allowedTime: 160, deductionPercent: 12 },
    },
};
